/* =========================================================
   File: 05_customer_behavior.sql
   Project: Uber Data Analysis
   Description: This file focuses on customer behavior,
                loyalty, retention, and usage patterns.
   Database: SQL Server
   Table: uber_data
   ========================================================= */


/* =========================================================
   1. Total Unique Customers
   Description: Counts the number of unique customers.
   ========================================================= */
SELECT COUNT(DISTINCT [Customer ID]) AS total_unique_customers
FROM uber_data;


/* =========================================================
   2. Rides per Customer
   Description: Shows how many rides each customer made.
   ========================================================= */
SELECT 
    [Customer ID],
    COUNT(*) AS total_rides
FROM uber_data
GROUP BY [Customer ID]
ORDER BY total_rides DESC;


/* =========================================================
   3. Average Rides per Customer
   Description: Calculates the average number of rides per customer.
   ========================================================= */
SELECT 
    AVG(customer_rides) AS avg_rides_per_customer
FROM (
    SELECT 
        [Customer ID],
        COUNT(*) AS customer_rides
    FROM uber_data
    GROUP BY [Customer ID]
) t;


/* =========================================================
   4. One-time Customers
   Description: Identifies customers who only used the service once.
   ========================================================= */
SELECT 
    COUNT(*) AS one_time_customers
FROM (
    SELECT 
        [Customer ID],
        COUNT(*) AS total_rides
    FROM uber_data
    GROUP BY [Customer ID]
    HAVING COUNT(*) = 1
) t;


/* =========================================================
   5. Repeat Customers
   Description: Identifies customers who used the service more than once.
   ========================================================= */
SELECT 
    COUNT(*) AS repeat_customers
FROM (
    SELECT 
        [Customer ID],
        COUNT(*) AS total_rides
    FROM uber_data
    GROUP BY [Customer ID]
    HAVING COUNT(*) > 1
) t;


/* =========================================================
   6. Customer Segmentation by Ride Count
   Description: Segments customers into usage groups.
   ========================================================= */
SELECT 
    CASE 
        WHEN ride_count = 1 THEN 'One-time'
        WHEN ride_count BETWEEN 2 AND 5 THEN 'Occasional'
        WHEN ride_count BETWEEN 6 AND 15 THEN 'Regular'
        ELSE 'Heavy User'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM (
    SELECT 
        [Customer ID],
        COUNT(*) AS ride_count
    FROM uber_data
    GROUP BY [Customer ID]
) t
GROUP BY 
    CASE 
        WHEN ride_count = 1 THEN 'One-time'
        WHEN ride_count BETWEEN 2 AND 5 THEN 'Occasional'
        WHEN ride_count BETWEEN 6 AND 15 THEN 'Regular'
        ELSE 'Heavy User'
    END;


/* =========================================================
   7. Revenue per Customer
   Description: Shows how much revenue each customer generated.
   ========================================================= */
SELECT 
    [Customer ID],
    SUM([Booking Value]) AS total_revenue
FROM uber_data
WHERE [Booking Status] = 'Completed'
GROUP BY [Customer ID]
ORDER BY total_revenue DESC;


/* =========================================================
   8. Average Revenue per Customer
   Description: Calculates average revenue generated by each customer.
   ========================================================= */
SELECT 
    AVG(customer_revenue) AS avg_revenue_per_customer
FROM (
    SELECT 
        [Customer ID],
        SUM([Booking Value]) AS customer_revenue
    FROM uber_data
    WHERE [Booking Status] = 'Completed'
    GROUP BY [Customer ID]
) t;


/* =========================================================
   9. Top 10 Customers by Revenue
   Description: Identifies the top 10 highest spending customers.
   ========================================================= */
SELECT TOP 10
    [Customer ID],
    SUM([Booking Value]) AS total_revenue
FROM uber_data
WHERE [Booking Status] = 'Completed'
GROUP BY [Customer ID]
ORDER BY total_revenue DESC;


/* =========================================================
   10. Cancellation Rate per Customer
   Description: Calculates cancellation rate per customer.
   ========================================================= */
SELECT 
    [Customer ID],
    CAST(SUM(CASE 
        WHEN [Cancelled Rides by Customer] = 'Yes'
          OR [Cancelled Rides by Driver] = 'Yes'
        THEN 1 ELSE 0 END) AS FLOAT)
    / COUNT(*) * 100 AS cancellation_rate
FROM uber_data
GROUP BY [Customer ID]
ORDER BY cancellation_rate DESC;


/* =========================================================
   11. Average Rating per Customer
   Description: Calculates the average rating given by each customer.
   ========================================================= */
SELECT 
    [Customer ID],
    AVG([Customer Rating]) AS avg_rating
FROM uber_data
WHERE [Customer Rating] IS NOT NULL
GROUP BY [Customer ID]
ORDER BY avg_rating DESC;


/* =========================================================
   12. Loyal Customers
   Description: Identifies customers with more than 10 rides.
   ========================================================= */
SELECT 
    [Customer ID],
    COUNT(*) AS total_rides
FROM uber_data
GROUP BY [Customer ID]
HAVING COUNT(*) > 10
ORDER BY total_rides DESC;


/* =========================================================
   13. First Ride Date per Customer
   Description: Shows the first ride date for each customer.
   ========================================================= */
SELECT 
    [Customer ID],
    MIN([Date]) AS first_ride_date
FROM uber_data
GROUP BY [Customer ID];


/* =========================================================
   14. Last Ride Date per Customer
   Description: Shows the last ride date for each customer.
   ========================================================= */
SELECT 
    [Customer ID],
    MAX([Date]) AS last_ride_date
FROM uber_data
GROUP BY [Customer ID];


/* =========================================================
   15. Customer Lifespan
   Description: Calculates the time span between first and last ride.
   ========================================================= */
SELECT 
    [Customer ID],
    DATEDIFF(DAY, MIN([Date]), MAX([Date])) AS lifespan_days
FROM uber_data
GROUP BY [Customer ID]
ORDER BY lifespan_days DESC;
