/* =========================================================
   Uber Data Analysis Project - KPI Queries
   Database: SQL Server
   Table Name: uber_data
   ========================================================= */

/* =========================================================
   1. Total Bookings
   Description: Calculates the total number of bookings in the dataset.
   ========================================================= */
SELECT COUNT([Booking ID]) AS total_bookings
FROM uber;


/* =========================================================
   2. Completed Bookings
   Description: Counts the number of successfully completed rides.
   ========================================================= */
SELECT COUNT(*) AS completed_bookings
FROM uber
WHERE [Booking Status] = 'Completed';


/* =========================================================
   3. Cancelled Bookings
   Description: Counts the total number of cancelled rides (by customer or driver).
   ========================================================= */
SELECT COUNT(*) AS cancelled_bookings
FROM uber
WHERE [Cancelled Rides by Customer] = 'Yes'
   OR [Cancelled Rides by Driver] = 'Yes';


/* =========================================================
   4. Cancellation Rate (%)
   Description: Calculates the percentage of cancelled rides from total bookings.
   ========================================================= */
SELECT 
    CAST(SUM(CASE 
        WHEN [Cancelled Rides by Customer] = 'Yes' 
          OR [Cancelled Rides by Driver] = 'Yes' 
        THEN 1 ELSE 0 END) AS FLOAT) 
    / COUNT(*) * 100 AS cancellation_rate
FROM uber;


/* =========================================================
   5. Total Revenue
   Description: Calculates the total revenue from completed rides only.
   ========================================================= */
SELECT SUM([Booking Value]) AS total_revenue
FROM uber
WHERE [Booking Status] = 'Completed';


/* =========================================================
   6. Average Booking Value
   Description: Calculates the average price of a completed ride.
   ========================================================= */
SELECT AVG([Booking Value]) AS avg_booking_value
FROM uber
WHERE [Booking Status] = 'Completed';


/* =========================================================
   7. Lost Revenue
   Description: Calculates the revenue lost due to cancelled or incomplete rides.
   ========================================================= */
SELECT SUM([Booking Value]) AS lost_revenue
FROM uber
WHERE [Cancelled Rides by Customer] = 'Yes'
   OR [Cancelled Rides by Driver] = 'Yes'
   OR [Incomplete Rides] = 'Yes';


/* =========================================================
   8. Total Distance
   Description: Calculates the total distance covered by completed rides.
   ========================================================= */
SELECT SUM([Ride Distance]) AS total_distance
FROM uber
WHERE [Booking Status] = 'Completed';


/* =========================================================
   9. Average Distance
   Description: Calculates the average ride distance.
   ========================================================= */
SELECT AVG([Ride Distance]) AS avg_distance
FROM uber
WHERE [Booking Status] = 'Completed';


/* =========================================================
   10. Average Driver Rating
   Description: Calculates the average rating given to drivers.
   ========================================================= */
SELECT AVG([Driver Ratings]) AS avg_driver_rating
FROM uber
WHERE [Driver Ratings] IS NOT NULL;


/* =========================================================
   11. Average Customer Rating
   Description: Calculates the average rating given by customers.
   ========================================================= */
SELECT AVG([Customer Rating]) AS avg_customer_rating
FROM uber
WHERE [Customer Rating] IS NOT NULL;


/* =========================================================
   12. Revenue by Vehicle Type
   Description: Shows total revenue generated by each vehicle type.
   ========================================================= */
SELECT 
    [Vehicle Type],
    SUM([Booking Value]) AS total_revenue
FROM uber
WHERE [Booking Status] = 'Completed'
GROUP BY [Vehicle Type]
ORDER BY total_revenue DESC;


/* =========================================================
   13. Bookings by Vehicle Type
   Description: Counts total bookings for each vehicle type.
   ========================================================= */
SELECT 
    [Vehicle Type],
    COUNT(*) AS total_bookings
FROM uber
GROUP BY [Vehicle Type]
ORDER BY total_bookings DESC;


/* =========================================================
   14. Cancellation Rate by Vehicle Type
   Description: Calculates the cancellation rate for each vehicle type.
   ========================================================= */
SELECT 
    [Vehicle Type],
    CAST(SUM(CASE 
        WHEN [Cancelled Rides by Customer] = 'Yes' 
          OR [Cancelled Rides by Driver] = 'Yes' 
        THEN 1 ELSE 0 END) AS FLOAT) 
    / COUNT(*) * 100 AS cancellation_rate
FROM uber
GROUP BY [Vehicle Type];


/* =========================================================
   15. Monthly Revenue
   Description: Shows revenue grouped by year and month.
   ========================================================= */
SELECT 
    YEAR([Date]) AS year,
    MONTH([Date]) AS month,
    SUM([Booking Value]) AS revenue
FROM uber
WHERE [Booking Status] = 'Completed'
GROUP BY YEAR([Date]), MONTH([Date])
ORDER BY year, month;


/* =========================================================
   16. Monthly Bookings
   Description: Shows total bookings per month.
   ========================================================= */
SELECT 
    YEAR([Date]) AS year,
    MONTH([Date]) AS month,
    COUNT(*) AS total_bookings
FROM uber
GROUP BY YEAR([Date]), MONTH([Date])
ORDER BY year, month;


/* =========================================================
   17. Top 10 Pickup Locations
   Description: Returns the top 10 pickup locations by number of bookings.
   ========================================================= */
SELECT TOP 10
    [Pickup Location],
    COUNT(*) AS total_bookings
FROM uber
GROUP BY [Pickup Location]
ORDER BY total_bookings DESC;


/* =========================================================
   18. Top 10 Drop Locations
   Description: Returns the top 10 drop locations by number of bookings.
   ========================================================= */
SELECT TOP 10
    [Drop Location],
    COUNT(*) AS total_bookings
FROM uber
GROUP BY [Drop Location]
ORDER BY total_bookings DESC;


/* =========================================================
   19. Customer Cancellation Reasons
   Description: Shows the most common cancellation reasons by customers.
   ========================================================= */
SELECT 
    [Reason for cancelling by Customer],
    COUNT(*) AS total
FROM uber
WHERE [Cancelled Rides by Customer] = 'Yes'
GROUP BY [Reason for cancelling by Customer]
ORDER BY total DESC;


/* =========================================================
   20. Driver Cancellation Reasons
   Description: Shows the most common cancellation reasons by drivers.
   ========================================================= */
SELECT 
    [Driver Cancellation Reason],
    COUNT(*) AS total
FROM uber
WHERE [Cancelled Rides by Driver] = 'Yes'
GROUP BY [Driver Cancellation Reason]
ORDER BY total DESC;
